services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Jose\Component\KeyManagement\KeyAnalyzer\KeyAnalyzerManager: ~
    Jose\Component\KeyManagement\KeyAnalyzer\AlgorithmAnalyzer: ~
    Jose\Component\KeyManagement\KeyAnalyzer\UsageAnalyzer: ~
    Jose\Component\KeyManagement\KeyAnalyzer\KeyIdentifierAnalyzer: ~
    Jose\Component\KeyManagement\KeyAnalyzer\NoneAnalyzer: ~
    Jose\Component\KeyManagement\KeyAnalyzer\OctAnalyzer: ~
    Jose\Component\KeyManagement\KeyAnalyzer\RsaAnalyzer: ~
    Jose\Component\KeyManagement\KeyAnalyzer\ES256KeyAnalyzer: ~
    Jose\Component\KeyManagement\KeyAnalyzer\ES384KeyAnalyzer: ~
    Jose\Component\KeyManagement\KeyAnalyzer\ES512KeyAnalyzer: ~
    Jose\Component\KeyManagement\KeyAnalyzer\HS256KeyAnalyzer: ~
    Jose\Component\KeyManagement\KeyAnalyzer\HS384KeyAnalyzer: ~
    Jose\Component\KeyManagement\KeyAnalyzer\HS512KeyAnalyzer: ~
    Jose\Component\KeyManagement\KeyAnalyzer\ZxcvbnAnalyzer: ~
